<?php

/**
 * @file
 * Installation and update functions for the Group Legal module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function glegal_install() {

  // Set 'view Terms and Conditions' permission to enabled by default.
  if (\Drupal::moduleHandler()->moduleExists('user')) {
    user_role_grant_permissions(RoleInterface::ANONYMOUS_ID, ['view Groups Terms and Conditions']);
    user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, ['view Groups Terms and Conditions']);
  }
}

/**
 * Implements hook_update_last_removed().
 */
function glegal_update_last_removed() {
  return 7103;
}
